### ISSUE TITLE
Compilation failure on Ubuntu

### ISSUE THREAD

**Issue by nasirchem** [NNairIITK/Vreco_CPMD#1]
I have been trying to compile Vreco_CPMD since last week on Ubuntu18.04 bionic, which is installed on my laptop; but every effort is ended into failure. Up to configure every thing goes well but when  I try make I get error message 

```bash
"Vreco_CPMD.f90:248: Error: Can't open included file 'mpif.h".
```

 I feel it is due to compiler `gfortran` and the `mpi` library, I have tried with the `intel compiler` but it is not working. I have attached all files that are generated by `./configure`. I searched for the problem, the few explanations were there but that did not work for me. I think It is not a bug It  may be happening due to my little knowledge. kindly help me to resolve this problem. a quick response will be appreciated greatly. Thank you very much.  

```bash
Error 
make[1]: Entering directory '/home/nasir/software/Vreco_CPMD-master'
Making all in src
make[2]: Entering directory '/home/nasir/software/Vreco_CPMD-master/src'
gfortran  -g -O2 -c -o Vreco_CPMD.o  Vreco_CPMD.f90
Vreco_CPMD.f90:248: Error: Can't open included file 'mpif.h'
Makefile:384: recipe for target 'Vreco_CPMD.o' failed
make[2]: *** [Vreco_CPMD.o] Error 1
make[2]: Leaving directory '/home/nasir/software/Vreco_CPMD-master/src'
Makefile:372: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/nasir/software/Vreco_CPMD-master'
Makefile:313: recipe for target 'all' failed
make: *** [all] Error 2

VRECO_CPMD configuration summary:
=================================
Basics:
  Fortran90 compiler:        gfortran
  Fortran90 flags:           -g -O2
  Fortran77 compiler:        
  Fortran77 flags:           -O2
  Linker flags:              
  Linked libraries:           

Build:
  Dynamic library:           

Options:
  With OpenMP:               -fopenmp
  With MPI:                  
   | include dir.:           
   | linker flags:           
   | linked libraries:       
   | MPI_INIT_THREAD avail:  
   | MPI2 support:           
  With dgemmsy support:      
  With libyaml:              
   | C flags:                
   | linked libraries:       
Installation paths:
  Source code location:      .
  Prefix:                    /usr/local
  Exec prefix:               ${prefix}
  Binaries:                  ${exec_prefix}/bin
  Static libraries:          ${exec_prefix}/lib
  Fortran modules:           
Documentation:             ${datarootdir}/doc/${PACKAGE_TARNAME}
```

With kind Regards,
Nasir Shahzad
PhD student 
Theoretical and Computational Chemistry Lab,
Center for Design and Application of Molecular Catalysts
INHA University, South Korea
email. nasirchem@yahoo.com
cell# 00821058658650

**Comment by HaoZeke** [comment]
Actually, MPI has not been fully implemented on the master branch, so I have stabilized the current master branch without it.

Please pull the latest version.

Additionally the problem described above is a linker problem, ie. `gfortran` does not know where your library is located. Once `mpi` support is actually implemented you should try passing an include (`-I`) flag to the compiler with the location of `mpif.h'
